import type { Metadata } from 'next';
import { Inter, Syncopate } from 'next/font/google';
import './globals.css';
import AppContainer from './AppContainer';

const inter = Inter({ subsets: ['latin'] });
const syncopate = Syncopate({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<AppContainer>{children}</AppContainer>
			</body>
		</html>
	);
}
